import { User } from './UserEntity';

export const usersData: User[] = [
  {
    id: '1',
    name: 'John',
    email: 'john@mail.com',
    role: 'admin',
    sex: 'male',
    active: true,
  },
  {
    id: '2',
    name: 'Peter',
    email: 'peter@mail.com',
    role: 'user',
    sex: 'male',
    active: true,
  },
  {
    id: '3',
    name: 'Mark',
    email: 'mark@mail.com',
    role: 'user',
    sex: 'male',
    active: true,
  },
  {
    id: '4',
    name: 'Marcus',
    email: 'marcus@mail.com',
    role: 'user',
    sex: 'male',
    active: false,
  },
  {
    id: '5',
    name: 'Maria',
    email: 'maria@mail.com',
    role: 'user',
    sex: 'female',
    active: true,
  },
  {
    id: '6',
    name: 'Helen',
    email: 'helen@mail.com',
    role: 'user',
    sex: 'female',
    active: false,
  },
  {
    id: '7',
    name: 'Julius',
    email: 'julius@mail.com',
    role: 'admin',
    sex: 'male',
    active: false,
  },
  {
    id: '8',
    name: 'Julia',
    email: 'julia@mail.com',
    role: 'admin',
    sex: 'female',
    active: false,
  },
  {
    id: '9',
    name: 'Violet',
    email: 'violet@mail.com',
    role: 'user',
    sex: 'female',
    active: true,
  },
  {
    id: '10',
    name: 'David',
    email: 'david@mail.com',
    role: 'user',
    sex: 'male',
    active: true,
  },
];
